### ISSUE TITLE
Please kindly add some explanation about 'hunger'.

### ISSUE THREAD

**Issue by hochae2018** [YoonSeongKyeong/Coding-Highway#1]
Dear,
I found that you used "protected" modifier for 'hunger'.
Would you please kindly let me know the reason why you used the key word for hunger?

Thanks and best regards,
hochae

**Comment by YoonSeongKyeong** [comment]
thank you for opening issue for my code, I checked the code and find that I was only mistakenly use protected instead of private!.. 
I will change this code. Thank you for giving me issue! 
and sorry for checking this late...
have a nice day!
