### ISSUE TITLE
성경 학우님 ButtonGame 클래스 살펴보았습니다.

### ISSUE THREAD

**Issue by praise-kim** [YoonSeongKyeong/Coding-Highway#2]
ButtonGame 클래스 살펴봤습니다. 코드가 명료하면서도 원래 모르던 기능들이 있어 배우고 갑니다. 특히 컬러 배열이랑 수식 이용해서 색 바꾸는 기능, 그리고 버튼 위치 랜덤하게 바뀌는 기능이 맘에 드네요. 저도 참고하겠습니다.

**Comment by YoonSeongKyeong** [comment]
감사합니다! 어떤 부분이 인상깊었는지 말씀해 주셔서 더 감사합니다! 
제 코드를 봐주셔서 감사드리고, 또 저도 더 유용한 것들 찾아서 사용해보겠습니다! 
너무 늦게 확인해서 죄송합니다.. 좋은하루 보내세요!!
